// Episode 4 - Arsen Lupin Autobiography (Part 4)

export const episode4 = {
  title: "Arsen Lupin — Autobiography (Part 4)",
  paragraphs: [
    {
      english: "The new path I had chosen began quietly. There was no sudden event, no dramatic signal announcing a transformation. Instead, it was a slow shift—one made of countless tiny decisions. I found myself drawn to situations where others turned away: small injustices, hidden errors, the silent suffering of people who had no voice strong enough to reach those in authority.",
      french: "Le nouveau chemin que j'avais choisi a commencé tranquillement. Il n'y a eu aucun événement soudain, aucun signal dramatique annonçant une transformation. Au lieu de cela, c'était un changement lent—fait d'innombrables petites décisions. Je me suis trouvé attiré par des situations où d'autres se détournaient : petites injustices, erreurs cachées, la souffrance silencieuse de personnes qui n'avaient pas de voix assez forte pour atteindre ceux qui détenaient l'autorité."
    },
    {
      english: "My first steps into this work were modest. I began helping workers resolve disputes about payment, orphans recover stolen property, widows understand official letters, and small shop owners deal with unfair tax demands. My knowledge of the world—and of people—became my primary tool. I learned to read the line between truth and lies not from words, but from pauses, glances, and the shape of a person's breath.",
      french: "Mes premiers pas dans ce travail étaient modestes. J'ai commencé à aider les travailleurs à résoudre des conflits concernant le paiement, les orphelins à récupérer des biens volés, les veuves à comprendre des lettres officielles, et les petits commerçants à faire face à des demandes d'impôts injustes. Ma connaissance du monde—et des gens—est devenue mon outil principal. J'ai appris à lire la ligne entre la vérité et les mensonges non pas dans les mots, mais dans les pauses, les regards, et la forme de la respiration d'une personne."
    },
    {
      english: "To many, my efforts seemed unnecessary. \"Why trouble yourself?\" they would ask. \"You owe these people nothing. There is no profit for you.\" But I had come to understand that a life concerned only with one's own gain is a narrow one, a life without real substance. I was not seeking credit, nor fame, nor recognition. I only wanted my actions to create small pockets of fairness in a world that often turned a blind eye to suffering.",
      french: "Pour beaucoup, mes efforts semblaient inutiles. \"Pourquoi vous donner du mal ?\" demandaient-ils. \"Vous ne devez rien à ces gens. Il n'y a aucun profit pour vous.\" Mais j'avais compris qu'une vie préoccupée uniquement par son propre gain est une vie étroite, une vie sans substance réelle. Je ne cherchais ni crédit, ni gloire, ni reconnaissance. Je voulais seulement que mes actions créent de petites poches d'équité dans un monde qui fermait souvent les yeux sur la souffrance."
    },
    {
      english: "What I did not expect, however, was how quickly my reputation grew. Word travels fast in a busy city, moving like steam from a boiling kettle—quiet at first, then impossible to contain. People began to knock on my door, sometimes late in the evening, sometimes before sunrise, each bringing a new problem, a new question, or a new plea for help. A missing jewel, a false accusation, a broken agreement, a mysterious disappearance of goods from a warehouse, a dispute over a lost parcel—my days filled with a strange mixture of simple domestic conflicts and unsettling puzzles.",
      french: "Ce à quoi je ne m'attendais pas, cependant, c'était la rapidité avec laquelle ma réputation grandissait. La rumeur voyage vite dans une ville animée, se déplaçant comme la vapeur d'une bouilloire bouillante—tranquille au début, puis impossible à contenir. Les gens ont commencé à frapper à ma porte, parfois tard le soir, parfois avant le lever du soleil, chacun apportant un nouveau problème, une nouvelle question, ou une nouvelle supplication d'aide. Un bijou manquant, une fausse accusation, un accord rompu, une disparition mystérieuse de marchandises d'un entrepôt, un différend sur un colis perdu—mes journées se sont remplies d'un mélange étrange de conflits domestiques simples et de puzzles troublants."
    },
    {
      english: "At first, I handled each case with calm precision. But as time passed, the matters grew more complex. I found myself navigating tangled webs of lies, hidden motives, secret meetings, and dangerous characters. I learned that even in ordinary neighborhoods, under the roof of common houses, there were secrets as dark as any found in the pages of fiction.",
      french: "Au début, j'ai traité chaque affaire avec une précision calme. Mais avec le temps, les affaires sont devenues plus complexes. Je me suis retrouvé à naviguer dans des toiles d'araignée emmêlées de mensonges, de motifs cachés, de réunions secrètes et de personnages dangereux. J'ai appris que même dans les quartiers ordinaires, sous le toit de maisons communes, il y avait des secrets aussi sombres que ceux trouvés dans les pages de fiction."
    },
    {
      english: "My work demanded new skills. I learned how to move silently, how to study a room without appearing to look, how to follow a man through a crowded market without attracting attention. I learned the art of patience—how to wait in the cold for hours, listening to the sound of distant traffic, watching the faint flicker of a lamp in an upstairs window. I learned how to interpret the shape of footprints in mud, the purpose of an unfamiliar tool, the meaning behind a misplaced object. Every detail became important: a torn thread on a jacket, a faint smell of soap, a tiny mark on a paper, a key left in the wrong lock.",
      french: "Mon travail exigeait de nouvelles compétences. J'ai appris à me déplacer silencieusement, à étudier une pièce sans avoir l'air de regarder, à suivre un homme à travers un marché bondé sans attirer l'attention. J'ai appris l'art de la patience—comment attendre dans le froid pendant des heures, écoutant le son de la circulation lointaine, regardant la faible lueur d'une lampe dans une fenêtre à l'étage. J'ai appris à interpréter la forme des empreintes de pas dans la boue, le but d'un outil inconnu, la signification derrière un objet mal placé. Chaque détail est devenu important : un fil déchiré sur une veste, une faible odeur de savon, une petite marque sur un papier, une clé laissée dans la mauvaise serrure."
    },
    {
      english: "But with each new challenge, I also came face-to-face with danger. Once, while investigating a string of thefts, I was cornered in a narrow alley by two men with rough hands and silent steps. They tried to force me into a dark yard, but I escaped by climbing a loose pipe, scraping my hands, tearing my shirt, and leaping onto a low roof. Another time, I nearly drowned in a river while chasing a man who had stolen not money, but important documents that held the fate of a widow's home. I learned the hard way that even the search for justice demands its own form of sacrifice.",
      french: "Mais avec chaque nouveau défi, je me suis aussi retrouvé face à face avec le danger. Une fois, alors que j'enquêtais sur une série de vols, j'ai été coincé dans une ruelle étroite par deux hommes aux mains rudes et aux pas silencieux. Ils ont essayé de me forcer dans une cour sombre, mais j'ai échappé en grimpant un tuyau lâche, me grattant les mains, déchirant ma chemise, et sautant sur un toit bas. Une autre fois, j'ai failli me noyer dans une rivière en poursuivant un homme qui avait volé non pas de l'argent, mais des documents importants qui détenaient le sort de la maison d'une veuve. J'ai appris à la dure que même la recherche de la justice exige sa propre forme de sacrifice."
    },
    {
      english: "Yet despite the risk, I found myself more alive than ever. Each case sharpened my instincts, and each success strengthened my resolve. Slowly, I felt myself becoming the man I had long sought to be—not a hero, not a master, but a quiet guardian of small truths.",
      french: "Pourtant, malgré le risque, je me suis trouvé plus vivant que jamais. Chaque affaire aiguisait mes instincts, et chaque succès renforçait ma détermination. Lentement, je me suis senti devenir l'homme que j'avais longtemps cherché à être—pas un héros, pas un maître, mais un gardien tranquille de petites vérités."
    },
    {
      english: "One winter, during a late-night investigation, I stopped for a moment in a silent street, watching snow fall under the pale yellow light of a lamp. The air was cold, the night empty, the world still. And in that brief moment of stillness, I understood something important: every life, mine included, is built from an endless chain of small choices. Actions, not dreams, shape a man's true identity. Work, not wishes, defines his character.",
      french: "Un hiver, pendant une enquête tard dans la nuit, je me suis arrêté un moment dans une rue silencieuse, regardant la neige tomber sous la lumière jaune pâle d'une lampe. L'air était froid, la nuit vide, le monde immobile. Et dans ce bref moment de calme, j'ai compris quelque chose d'important : chaque vie, la mienne incluse, est construite à partir d'une chaîne sans fin de petits choix. Les actions, pas les rêves, façonnent la véritable identité d'un homme. Le travail, pas les souhaits, définit son caractère."
    },
    {
      english: "It was then that I decided to dedicate myself fully to this path—not as a temporary duty, but as a lifelong purpose.",
      french: "C'est alors que j'ai décidé de me consacrer pleinement à ce chemin—non pas comme un devoir temporaire, mais comme un but de toute une vie."
    }
  ]
}
